name: Monitor Folder for Changes to run script
on:
  push:
    branches:
      - master
    paths:
      - 'src/assets/**'
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run script
      run: |
        if [ -n "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} 'your-folder/')" ]; then
          bash i-did-it.sh
        else
          echo "No changes in the specified folder."
